Feature/paymentsystem openpos 73
ICTOOSDDd4/OpenPOS pull request #101
Opened 2022-12-06 20:47 UTC by VarioCode

2022-12-07 09:07 UTC, jortdr requested changes
Needs fixing, check review comments

2022-12-07 09:07 UTC, jortdr commented on OpenPOS-APP/MenuPage.xaml.cs
> +   private EventHubService _eventHubService;
Not used?

2022-12-07 09:07 UTC, jortdr commented on OpenPOS-APP/MenuPage.xaml.cs
> +   private EventHubService _eventHubService;
Fn seems to be removed that was using this var,

2022-12-07 09:07 UTC, jortdr commented on OpenPOS-APP/Services/EventHubService.cs
> +using System.Text;
Double using directive, twice

2022-12-07 09:07 UTC, jortdr commented on OpenPOS-APP/Services/EventHubService.cs
> +      private bool iWantItToStop = true;
bool not following naming scheme

2022-12-07 09:07 UTC, jortdr commented on OpenPOS-Testing/TransactionModelTest.cs
> +
Incomplete test

2022-12-08 10:11 UTC, jortdr commented on OpenPOS-APP/PaymentPage.xaml.cs
> +   // This way you can also handle the inisiate the event hub service and you can let the page wait before showing the QR code without adding it to the listener.
Comments?

2022-12-08 10:12 UTC, jortdr commented on OpenPOS-APP/PaymentPage.xaml.cs
>     private EventHandler<EventArgs> _eventHandler;
Field not used

2022-12-08 13:07 UTC, jortdr commented on OpenPOS-APP/Services/EventHubService.cs
>        private bool _isConnected = false;
bool is assigned but never used

2022-12-08 13:08 UTC, VarioCode commented on OpenPOS-APP/Services/EventHubService.cs
>        private bool _isConnected = false;
Needs too stay there for future use.

2022-12-08 13:09 UTC, VarioCode commented on OpenPOS-APP/OpenPOS-APP.csproj
> +		<!--<TargetFrameworks></TargetFrameworks-->
Fixed

2022-12-08 13:17 UTC, TinyTani commented on OpenPOS-APP/PaymentPage.xaml.cs
> +      _eventHubService.newPayent += OnPaymentPayed;
Please change to Payment

2022-12-08 14:05 UTC, jortdr approved these changes
Looks good

2022-12-08 14:05 UTC, merged