Feature/search openpos 36
ICTOOSDDd4/OpenPOS pull request #103
Opened 2022-12-07 12:26 UTC by rexxieboy

it works

2022-12-07 15:14 UTC, jortdr requested changes
Search will wipe labels (amount ordered) once search value changed. pls fix

2022-12-08 14:09 UTC, TinyTani approved these changes
ja

ja

ideaal

2022-12-08 14:13 UTC, TinyTani approved these changes
ja

ja

ja nee dit is echt top

2022-12-08 14:14 UTC, VarioCode approved these changes

2022-12-08 14:17 UTC, jortdr requested changes
Not good.

2022-12-08 14:17 UTC, jortdr commented on OpenPOS-APP/ProductView.xaml.cs
> +            Debug.WriteLine("asdasd");
:((((((((((( -1

2022-12-08 14:27 UTC, jortdr submitted a review, later dismissed
excellent

2022-12-08 14:32 UTC, jortdr approved these changes
ok

2022-12-08 14:34 UTC, TinyTani approved these changes
ja mann

2022-12-08 14:40 UTC, merged