Seed the database with roles
ICTOOSDDd4/OpenPOS pull request #89
Opened 2022-12-01 13:18 UTC by Tymen

2022-12-01 13:29 UTC, rexxieboy submitted a review, later dismissed
muy bien

2022-12-02 10:12 UTC, rexxieboy requested changes
missing barcrew

2022-12-02 10:15 UTC, rexxieboy approved these changes

2022-12-02 10:18 UTC, jortdr approved these changes
Looks good

2022-12-02 10:34 UTC, merged