Feature/custom exceptions openpos 60
ICTOOSDDd4/OpenPOS pull request #93
Opened 2022-12-02 11:01 UTC by rexxieboy

2022-12-03 10:21 UTC, Tymen commented
Resolve conflict first, Btw this PR is not custom exceptions really. It's more an logger (also cool) instead of exceptions

2022-12-03 11:51 UTC, VarioCode requested changes

2022-12-03 11:51 UTC, VarioCode commented on OpenPOS-APP/Exceptions/WriteToLogHandler.cs
> +            Directory.CreateDirectory(path);
Are you sure this will create a new file? And with a custom dynamic name for each exception that we want to log?

2022-12-03 11:54 UTC, VarioCode commented
This is partially the feature that we wanted to implement, is it possible you can look into creating a service that shows a popup for errors that you give it as a parameter? You just need to use the .NET MAUI Community Toolkit popup.

2022-12-07 14:33 UTC, jortdr commented
out of date @rexxieboy, is this still getting merged?

2022-12-08 14:16 UTC, VarioCode approved these changes
Nice logger

2022-12-08 14:17 UTC, TinyTani approved these changes
helemaal toppie

2022-12-08 14:33 UTC, merged