routed the enums
ICTOOSDDd4/OpenPOS pull request #97
Opened 2022-12-05 13:30 UTC by TinyTani

2022-12-06 07:26 UTC, VarioCode commented
Please resolve the conflict first.

2022-12-06 08:03 UTC, jortdr requested changes
Resolve conflicts

2022-12-07 11:04 UTC, jortdr commented
There are still conflicts here.

2022-12-07 14:24 UTC, jortdr requested changes
Check comments

2022-12-07 14:24 UTC, jortdr commented on OpenPOS-APP/MenuPage.xaml.cs
> +       if (HorizontalLayout == null || HorizontalLayout.Children.Count % moduloNumber == 0)
HorizontalLayout needs to be refactored

2022-12-08 16:58 UTC, jortdr approved these changes

2022-12-08 16:59 UTC, merged